spring.application.name=sistema
spring.datasource.url=jdbc:postgresql://dpg-d496j09r0fns738dmvn0-a/rd_sistema
spring.datasource.username=diego
spring.datasource.password=aXH9VfRpa7jMU18rGdyCvXpE8zYvOInR

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=9090

